### ISSUE TITLE
Support use of different volumes with Docker

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#1649]
#### Summary
Scenario is the same as described into #1620: I want to separate directories `keys`, `localstore` and `statestore` into `.bee` folder mounting different named volumes. This is useful for backup data, differentiating each volume with a different backup schema.

Currently when I start a new container with this configuration, it ends with these logs:

```
time="2021-05-03T15:52:50Z" level=info msg="version: 0.5.3-acbd0e2"
time="2021-05-03T15:52:50Z" level=warning msg="clef is not enabled; portability and security of your keys is sub optimal"
Error: swarm key: open /home/bee/.bee/keys/swarm.key: permission denied
```

Current permission mounting folders are:

```
drwxr-xr-x 3 bee  bee  4096 May  3 16:26 .
drwxr-xr-x 1 bee  bee  4096 Mar 23 08:15 ..
drwxr-xr-x 2 root root 4096 May  3 16:17 keys
drwxr-xr-x 2 root root 4096 May  3 16:17 localstore
drwxr-xr-x 2 root root 4096 May  3 16:17 statestore
```

they should be created and adjusted as for `/home/bee/.bee`.

#### Steps to reproduce
Try to deploy this with Docker compose or Stack. Change the Swap endpoint:

```
version: "3.8"

services:
  bee:
    image: ethersphere/bee:0.5.3
    volumes:
      - beeDebug-keys:/home/bee/.bee/keys
      - beeDebug-localstore:/home/bee/.bee/localstore
      - beeDebug-statestore:/home/bee/.bee/statestore
    command: start
    environment:
      - BEE_PASSWORD=123456
      - BEE_SWAP_ENDPOINT=<set_me>
    ports:
      - 1633:1633 #gateway api
      - 1634:1634 #p2p
      - 1635:1635 #debug api

volumes:
  beeDebug-keys:
  beeDebug-localstore:
  beeDebug-statestore:
```

#### Expected behavior
Volumes should be normally populated, and node should ask for fund the new generated address.

#### Actual behavior
It immediately stops with a "permission denied" error.
