### ISSUE TITLE
Docker compose create one more bee instance can not receive peers

### ISSUE THREAD

**Issue by dingguijin** [ethersphere/bee#1656]
# Docker compose create one more bee instance can not receive peers

## Story

Docker compose create one bee instance with default settings, it can works well, and after a while, testing with `curl localhost:1635/peers`, a lot of peers show.

But create a new bee instance with docker compose with different ports, every port plus 4, for instance, the p2p addr port 1638, the debug api port 1639.

The bee instance starts up and pass the initial geth payout. after a while (even long time, 4 hours and more), the log of the bee instance:

```
bee-1_1   | time="2021-05-04T23:44:35Z" level=warning msg="discover to bootnode /dnsaddr/bootnode.ethswarm.org"
bee-1_1   | time="2021-05-04T23:45:07Z" level=warning msg="connect to bootnode /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW"
bee-1_1   | time="2021-05-04T23:45:07Z" level=warning msg="discover to bootnode /dnsaddr/bootnode.ethswarm.org"
bee-1_1   | time="2021-05-04T23:45:39Z" level=warning msg="connect to bootnode /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW"
bee-1_1   | time="2021-05-04T23:45:39Z" level=warning msg="discover to bootnode /dnsaddr/bootnode.ethswarm.org"
bee-1_1   | time="2021-05-04T23:46:10Z" level=warning msg="connect to bootnode /ip4/100.26.242.174/tcp/31301/p2p/16Uiu2HAmHgthsmN99SDMaApv5XY2YaCLeU9gkrPWBzRWBCaLPphs"
bee-1_1   | time="2021-05-04T23:46:10Z" level=warning msg="discover to bootnode /dnsaddr/bootnode.ethswarm.org"
bee-1_1   | time="2021-05-04T23:46:42Z" level=warning msg="connect to bootnode /ip4/52.90.206.204/tcp/31302/p2p/16Uiu2HAmMxanzFwGspp7dvpZymTSF28w4x2qbbqd9EmzC75dPiYB"
```

Check the debug api peers, it returns a empty list.

```
curl localhost:1639/peers
```

## Background

```
version: "3"

services:
  clef-1:
    image: ethersphere/clef:0.4.9
    restart: unless-stopped
    environment:
      - CLEF_DATA
      - CLEF_CHAINID
    volumes:
      - clef-1:/app/data
    command: full

  bee-1:
    image: ethersphere/bee:latest
    restart: unless-stopped
...
```

I use the latest version bee image.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|
