### ISSUE TITLE
Use "format: int64" into open api specification for integers where required

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#1726]
#### Summary
Currently OpenAPI specification declare some types as integers, but never declare the format, also where would be required.  
It's the case for example of `Cheque.payout` property schema, declared in `SwarmCommon.yaml` as.

```
    Cheque:
      type: object
      properties:
        beneficiary:
(...)
        payout:
          type: integer
```

where it should be:

```
    Cheque:
      type: object
      properties:
        beneficiary:
(...)
        payout:
          type: integer
          format: int64
```

Missing of `format: int64` implies that expected number will be an `int32` value. This lead for example into generating invalid client code, where this property is implemented as an `int` value instead of a `long`, generating errors on response parsing.

#### Expected behavior
Where API uses long numbers, schema should declare it as

```
type: integer
format: int64
```

#### Actual behavior
There is no declared differences between `int32` and `int64` values
```
type: integer
```
