### ISSUE TITLE
Generate `config.yaml`  with commented hints by default

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#3709]
when `bee printconfig` is run or whenever a config.yaml is generated automatically, it would be really helpful if there are explanatory hints/comments above the config parameters in the config.yaml files.

Current: `config.yaml`
```yaml
...
verbosity: info
welcome-message: ""
mainnet: false
...
```

Ideal: `config.yaml`
```yaml
...
# log verbosity level 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=trace (default "info")
verbosity: info
# send a welcome message string during handshakes
welcome-message: ""
# triggers connection to main network
mainnet: false
...
```
