### ISSUE TITLE
BEE_DEBUG_API_ENABLE being set to false causes "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by ed0sh** [ethersphere/bee#3986]
### Context
Bee v1.13.0 / Docker v20.10.17 / Ubuntu Server v22.04.2 LTS / Intel Celeron N5105

### Summary
After some seconds after starting the node with `docker compose up -d`, the node stops with the a panic error message in the logs.

### Expected behavior
A correct execution of the node without panicking

### Actual behavior
The node stops with the following error message:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf0 pc=0x1181ba1]

goroutine 41 [running]:
github.com/ethersphere/bee/pkg/api.(*Service).MetricsRegistry(...)
        github.com/ethersphere/bee/pkg/api/metrics.go:164
github.com/ethersphere/bee/pkg/node.NewBee({0x1aac638, 0xc000c9aa50}, {0x1527f4a, 0x5}, 0xc0002159a0, {0x1aaeb20?, 0xc0006123c0}, 0xa, {0x1ab7948, 0xc000c9aa00}, ...)
        github.com/ethersphere/bee/pkg/node/node.go:594 +0x34c1
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNode({0x1aac638, 0xc000c9aa50}, 0xc000c9a910, 0xc000f1a2c0?, {0x1ab7948, 0xc000c9aa00})
        github.com/ethersphere/bee/cmd/bee/cmd/start.go:295 +0x14d6
github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync.func1()
        github.com/ethersphere/bee/cmd/bee/cmd/start.go:200 +0x3a
created by github.com/ethersphere/bee/cmd/bee/cmd.buildBeeNodeAsync
        github.com/ethersphere/bee/cmd/bee/cmd/start.go:199 +0x110
```

### Steps to reproduce
docker-compose.yml

```
version: "3"

services:
  clef-1:
    image: ethersphere/clef:0.6.0
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - CLEF_CHAINID=5
    volumes:
      - clef-1:/app/data
    command: full
    networks:
      - bee_net

  bee-1:
    image: ethersphere/bee:stable
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - BEE_API_ADDR
      - BEE_BLOCK_TIME
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-1:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_FULL_NODE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY_PERCENT
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE_PERCENT
      - BEE_POSTAGE_STAMP_ADDRESS
      - BEE_RESOLVER_OPTIONS
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_LEGACY_FACTORY_ADDRESSES
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_SWAP_DEPLOYMENT_GAS_PRICE
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_TRANSACTION
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
      - BEE_MAINNET
    ports:
      - "${API_ADDR:-1633}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1634}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-127.0.0.1:1635}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - bee-1:/home/bee/.bee
    command: start
    depends_on:
      - clef-1
    networks:
      - bee_net

volumes:
  clef-1:
  bee-1:

networks:
  bee_net:
    name: bee_net
    driver: bridge
```

.env (I voluntarily pasted the uncommented only env variables)

```
# Copy this file to .env, then update it with your own settings

### CLEF

## chain id to use for signing (100=mainnet(xdai), 5=testnet(goerli)) (default: 12345)
CLEF_CHAINID=5

### BEE

## enable clef signer
BEE_CLEF_SIGNER_ENABLE=true
## clef signer endpoint
BEE_CLEF_SIGNER_ENDPOINT=http://clef-1:8550
## cause the node to start in full mode
BEE_FULL_NODE=true
## NAT exposed address
BEE_NAT_ADDR=X.X.X.X:1634 (voluntarily blurred during paste, it's a static public ip address)
## ID of the Swarm network (default 1)
BEE_NETWORK_ID=10
BEE_BLOCKCHAIN_RPC_ENDPOINT=https://eth.getblock.io/****/goerli/ (voluntarily blurred during paste)
## password for decrypting keys
BEE_PASSWORD=#### (voluntarily blurred during paste)
## triggers connection to main network
BEE_MAINNET=false
```

### Possible solution
According to @mfw78 in the Discord channel, an easy way to bypass the bug was to set `BEE_DEBUG_API_ENABLE=true` in the .env file
