### ISSUE TITLE
Consistent quotation usage in config file

### ISSUE THREAD

**Issue by NoahMaizels** [ethersphere/bee#4691]
#### Summary

Quotation marks are not used consistently in the `bee.yaml` config file, see these options for example from the `bee printconfig` output:

```yaml
# percentage below the peers payment threshold when we initiate settlement
payment-early-percent: 50
# threshold in BZZ where you expect to get paid from your peers
payment-threshold: "13500000"
# excess debt above payment threshold in percentages where you disconnect from your peer
payment-tolerance-percent: 25
```
This has caused some problems for users:

- https://discord.com/channels/799027393297514537/811574542069137449/1195707351899066440
- https://discord.com/channels/799027393297514537/811553590170353685/1166411342647939083
- https://discord.com/channels/799027393297514537/811553590170353685/1035181054513926154

It should be changed so that quotation marks are used consistently

#### Motivation

To reduce friction for new users.
