### ISSUE TITLE
Auto-Neighborhood Balancing Feature

### ISSUE THREAD

**Issue by NoahMaizels** [ethersphere/bee#4991]
#### Summary

Currently, when a node joins the network, it uses the [Swarmscan neighborhood selector tool](https://api.swarmscan.io/v1/network/neighborhoods/suggestion) as the default value for `neighborhood-suggester` to choose a neighborhood based on choosing from among the least populated neighborhoods. This is great for the initial provisioning of nodes, but over time as neighborhood populations shift, it may end up that the neighborhood the node finds itself in is no longer ideal.

Currently, we recommend node operators to periodically check their node's neighborhood and hop to a new neighborhood if needed. However I am doubtful of how many node operators are actually following this practice (I just posted a [poll](https://discord.com/channels/799027393297514537/811553590170353685/1336816405621899314) on this matter in Discord, if it turns out my assumption is wrong, then maybe this isn't as much of an issue as I thought).

I believe that periodic automatic neighborhood balancing should be a feature which is on by default, with a sensible default configuration controlling when to hop or not according to current neighborhood population and current distribution of nodes in neighborhoods throughout the network. 

Potential options with some sensible default values included:

```yaml
neighborhood-rebalancing: <bool> # Defaults to `true`
neighborhood-rebalancing-interval: <int> # Days to wait until rechecking if a neighborhood hop is needed - default of 15?
max-neighbors: <int> # The maximum number of neighbors allowed. If exceeded, the `neighborhood-suggester` is used to hop to a new neighborhood. 
```

The `max-neighbors` option perhaps should not be included rather we should use the results from the Swarmscan [/network/neighborhoods](https://api.swarmscan.io/v1/network/neighborhoods) endpoint to calculate a reasonable number to use when checking whether to hop?

#### Motivation

There are several good reasons for this feature:

1. Easier UX for node operators - it allows them to automatically ensure their nodes will always move to the most profitable neighborhoods
2. Improves safety for data on the network - ensures that no neighborhoods are allowed to become underpopulated

#### Implementation

I don't have the ability to implement it.

#### Drawbacks

I see no reason not to.
