### ISSUE TITLE
Push sync cannot sync chunk

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#843]
# Task
This was identified, through looking at the tags. We saw that tag.sent was much higher than tag.split and it continued to increment, even after 4 hours of trying to push. 
![image](https://user-images.githubusercontent.com/33000441/96283050-dfaf6380-0fdb-11eb-9d97-bcd23225b8a4.png)

## Acceptance criterea

- push sync should eventually be done with pushing and don't get stuck in pushing the same chunks for hours.

**Comment by acud** [comment]
I'd suggest we rename the ticket here. the problem is not that the sent count is being incremented, but pushsync for some reason cannot sync the chunk

**Comment by Eknir** [comment]
@acud , done that. Tagging @zbiljic , as you recently put a lot of attention on the push sync. Perhaps you have an idea what went wrong here? 

@acud, I can try to reproduce, could you give me pointers on what information is relevant?

**Comment by ldeffenb** [comment]
I believe that if I had the tag ID, I'd see similar behavior on my many, many chunks that are still trying to push.  The error I'm seeing is:

time="2020-10-26T09:52:01-04:00" level=debug msg="pusher: error while sending chunk or receiving receipt: receive receipt from peer 7b8dcf3cc74795801ca6f6ef8c90c49ac82af0348eae1e2c18338cdccca55476: stream reset"

And the burst (probably 50 or more) of these tries over and over again as long as I keep the client running.  I've disconnected the apparently offending peer, but it just switches to a different one and keeps retrying.  I've even disconnected a set of 10 or so peers accumulated by incremental disconnects, but have not yet (after a few weeks) successfully pushed out these chunks.

**Comment by ldeffenb** [comment]
Actually, I just remembered that when I close the client, a bunch of tags (217 of them!) update.  I pulled a tag status on one of them and it says:

{
  "total": 59,
  "split": 59,
  "seen": 12,
  "stored": 59,
  "sent": 372,
  "synced": 46,
  "uid": 4049871528,
  "name": "unnamed_tag_1602087879",
  "address": "0e2463423d061c81fbfd15e9a0f07dbbb1c325390fe8836145f2f7a8a110d17e",
  "startedAt": "2020-10-07T12:24:39-04:00"
}

So since sent is much greater than total/split/stored, I suspect I've got the situation described in this issue.  And while typing this up, sent went from 372 to 379 on this tag.

**Comment by ldeffenb** [comment]
And here's what these retries look like in my outbound (top) network traffic:

https://gateway.ethswarm.org/files/2c91828128cb341382c1ecf42ac0500a57f1fe382e5b5b4d389a84912fc5b865

**Comment by Eknir** [comment]
This just happened to me again. `Sent` is incrementing above `Split`, and the video which I uploaded (small file, 700 chunks) cannot be retrieved.

**Comment by Eknir** [comment]
I used
`curl -v -H "Content-Type: video/mp4" --data-binary @birdshouse.mp4 localhost:8080/files?name=birdshouse.mp4`
to upload my video

The bee node is at the latest master version 

Config 

```yaml
api-addr: :8080
bootnode:
- /dnsaddr/bootnode.ethswarm.org
clef-signer-enable: false
clef-signer-endpoint: ""
config: /home/rinke/.bee.yaml
cors-allowed-origins: []
data-dir: /home/rinke/swarm/beeData/1
db-capacity: "5000000"
debug-api-addr: :6060
debug-api-enable: true
gateway-mode: false
global-pinning-enable: false
help: false
nat-addr: ""
network-id: "1"
p2p-addr: :7070
p2p-quic-enable: false
p2p-ws-enable: false
password: ""
password-file: ""
payment-early: "10000"
payment-threshold: "100000"
payment-tolerance: "10000"
resolver-options: []
standalone: false
swap-enable: true
swap-endpoint: https://rpc.slock.it/goerli 
swap-factory-address: ""
swap-initial-deposit: "100000000"
tracing-enable: false
tracing-endpoint: 127.0.0.1:6831
tracing-service-name: bee
verbosity: debug
```
