### ISSUE TITLE
Pushing blocks

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#893]
#### Summary

- I connect my node to the `staging` cluster. The config is:
```yaml
config/staging_no_swap.yaml 
debug-api-enable: true
debug-api-addr: :6061
api-addr: :8081
p2p-addr: :7071
swap-enable: false
data-dir: /tmp/bee/staging_no_swap
verbosity: trace
network-id: 2
bootnode: /dnsaddr/bootnode.staging.ethswarm.org
swap-endpoint: https://rpc.slock.it/goerli
welcome-message: "Welcome from Eknir without SWAP"
```
- The node is splitting, but pushing doesn't work. Initially, only 3 chunks are pushed. After about 1 minute 600 additional chunks are pushed, now, it is already blocked for a long time at 600 chunks.

#### Steps to reproduce

1. Start node with provided config
2. It stops after a while

#### Expected behavior

It looks to me that this happened because accounting doesn't allow me to cross thresholds. I would expect at least a message (in the console), saying that it cannot continue pushing because I cannot write a cheque.

**Comment by Eknir** [comment]
@metacertain , could you try to reproduce this for me, add any additional information and then assign it to low priority?

**Comment by Eknir** [comment]
Tried this again, with another node (config below). I can confirm that it is not because of the `--no-swap` flag. 

```yaml
debug-api-enable: true
data-dir: /tmp/bee/staging1
verbosity: trace
network-id: 2
bootnode: /dnsaddr/bootnode.staging.ethswarm.org
swap-endpoint: https://rpc.slock.it/goerli
welcome-message: "Welcome from Eknir"
```

![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/a6922e0c-7829-4f98-95e8-68850481708f)

[https://app.zenhub.com/files/234530887/794adbe2-831a-467c-a57e-013f25eb2f64/download](https://app.zenhub.com/files/234530887/794adbe2-831a-467c-a57e-013f25eb2f64/download)
