### ISSUE TITLE
Local node stops working when uploading larger file

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#894]
#### Summary
When uploading larger file (~300MiB), at one point node started only logging following error, two on one second intervals:

```
DEBU[2020-11-02T15:07:40+01:00] localstore push subscription iteration: index iterator function: get value: leveldb: not found
DEBU[2020-11-02T15:07:40+01:00] localstore push subscription iteration: index iterator function: get value: leveldb: not found
```

The thing that may relate to this problem is low configuration for `db-capacity`, which was `10000`.

#### Steps to reproduce
The node was connected to the `staging` network, with following configuration:

```yaml
data-dir: ~/tmp/bee/node
db-capacity: 10000
password: pass
debug-api-enable: true
tracing-enable: true
verbosity: trace
network-id: 2
bootnode:
- /dnsaddr/bootnode.staging.ethswarm.org
global-pinning-enable: false
swap-endpoint: https://rpc.slock.it/goerli
swap-enable: false
```

The file was being uploaded via `files` API.

The files was being uploaded with a tag, and this is the state at which upload stopped:

```json
{
    "address": "",
    "name": "unnamed_tag_1604325530",
    "seen": 1,
    "sent": 1674,
    "split": 31167,
    "startedAt": "2020-11-02T14:58:50+01:00",
    "stored": 31166,
    "synced": 1674,
    "total": 0,
    "uid": 2044808445
}
```

#### Expected behavior
The node should accept the upload, and push all chunks for the file.

#### Actual behavior
The node logged same 2 log lines every second, and upload was blocked.

@janos
